"""add_marketing_fields_to_leads

Revision ID: 0e227d9a6d90
Revises: aa8d575bebe5
Create Date: 2025-12-01 05:07:03.362916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e227d9a6d90'
down_revision = 'aa8d575bebe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'role')
    op.drop_column('leads', 'company_size')
    op.drop_column('leads', 'industry')
    # ### end Alembic commands ###

